//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auctions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidHistory
    {
        public int ID { get; set; }
        public Nullable<int> LinkID { get; set; }
        public Nullable<int> RollId { get; set; }
        public string Lot { get; set; }
        public Nullable<int> SellerId { get; set; }
        public Nullable<int> BuyerId { get; set; }
        public Nullable<decimal> BiddingPrice { get; set; }
        public Nullable<decimal> BidTotalPrice { get; set; }
        public Nullable<System.DateTime> DateTimeBid { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual tblRoll tblRoll { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblCustomer tblCustomer1 { get; set; }
        public virtual ltRollDescription ltRollDescription { get; set; }
        public virtual tblCustomer tblCustomer2 { get; set; }
    }
}
