//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auctions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultSetup
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
        public string BackgroundColor { get; set; }
        public string FontColor { get; set; }
        public Nullable<int> RefreshTime { get; set; }
        public Nullable<int> AuctionDelayTime { get; set; }
        public string LogoPath { get; set; }
        public string LogoName { get; set; }
        public string SmallLogoName { get; set; }
        public string RollImagesPath { get; set; }
        public Nullable<bool> SmsNotification { get; set; }
        public string LogoBackgroundColor { get; set; }
        public bool SMSAllFunctionality { get; set; }
        public bool SMSCustRegistration { get; set; }
        public bool SMSConfirmationLoginRequired { get; set; }
        public bool emailConfirmRegistration { get; set; }
        public bool emailConfirmationLoginRequired { get; set; }
        public string BackgroundColorHome { get; set; }
        public Nullable<int> DefaultAuction { get; set; }
        public Nullable<bool> smsOutBidder { get; set; }
        public Nullable<int> DispLines { get; set; }
        public Nullable<int> DispColumns { get; set; }
        public Nullable<int> RollDispRefreshRate { get; set; }
        public string HomePeriodDescription { get; set; }
        public string HomePeriodDescriptionTextColor { get; set; }
        public string HomePeriodDescriptionBackColor { get; set; }
        public string ActionTextColor { get; set; }
        public string ActionBackColor { get; set; }
        public string RollActionBidColor { get; set; }
        public string RollActionBackIndexColor { get; set; }
    
        public virtual ltRollDescription ltRollDescription { get; set; }
    }
}
