//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auctions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlexiBuyerNo
    {
        public string BSNR { get; set; }
        public Nullable<double> ID { get; set; }
        public string EVENT { get; set; }
        public string CUSTOMER { get; set; }
        public string CUST_NAME { get; set; }
        public Nullable<System.DateTime> UPD { get; set; }
        public string UPDBY { get; set; }
        public string VATNR { get; set; }
        public string QFIND { get; set; }
        public string ALT { get; set; }
        public string CEL { get; set; }
        public string TEL { get; set; }
        public string OPTIONAL_NOTE { get; set; }
        public string OPTIONAL_NAME { get; set; }
        public string VATNr1 { get; set; }
        public string ADDRESS { get; set; }
        public string EMAIL { get; set; }
        public string StudNr { get; set; }
        public Nullable<double> BSNR1 { get; set; }
        public string PAYM { get; set; }
        public int idKey { get; set; }
    }
}
