//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auctions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRoll()
        {
            this.BidHistories = new HashSet<BidHistory>();
        }
    
        public int ID { get; set; }
        public Nullable<int> RollId { get; set; }
        public string Lot { get; set; }
        public Nullable<int> SpeciesCode { get; set; }
        public string TagNr { get; set; }
        public string Age { get; set; }
        public string DateMeasured { get; set; }
        public string HornLength { get; set; }
        public string TipToTip { get; set; }
        public string OtherInfo { get; set; }
        public string DateAvailable { get; set; }
        public Nullable<int> Male { get; set; }
        public Nullable<int> Female { get; set; }
        public Nullable<int> Young { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Quantity_Lot { get; set; }
        public Nullable<int> SellerId { get; set; }
        public Nullable<int> BuyerId { get; set; }
        public Nullable<decimal> BiddingPrice { get; set; }
        public Nullable<System.DateTime> BidDateTime { get; set; }
        public Nullable<decimal> BidTotalPrice { get; set; }
        public Nullable<decimal> NewBidPrice { get; set; }
        public Nullable<int> NewBidder { get; set; }
        public byte[] Picture { get; set; }
        public bool OnAuction { get; set; }
        public bool Sold { get; set; }
        public Nullable<System.DateTime> DateLoaded { get; set; }
        public Nullable<System.DateTime> DateSold { get; set; }
        public string PicturePath { get; set; }
        public string PictureName { get; set; }
        public Nullable<decimal> Increments { get; set; }
        public Nullable<decimal> ReservePrice { get; set; }
        public Nullable<decimal> LotQ { get; set; }
        public Nullable<System.DateTime> DateTimeBid { get; set; }
        public Nullable<System.DateTime> DateTimeClose { get; set; }
        public string CustomerNumber { get; set; }
    
        public virtual ltRollDescription ltRollDescription { get; set; }
        public virtual ltRollDescription ltRollDescription1 { get; set; }
        public virtual ltSpecy ltSpecy { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblCustomer tblCustomer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidHistory> BidHistories { get; set; }
    }
}
